# Generated by Django 3.0.7 on 2020-06-06 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HangSanXuat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_hang', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HangHoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_hang', models.CharField(max_length=255)),
                ('gia_tien', models.IntegerField(default=0)),
                ('hang', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.HangSanXuat')),
            ],
        ),
    ]
