# Generated by Django 3.0.7 on 2020-06-09 13:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_baiviet'),
    ]

    operations = [
        migrations.AddField(
            model_name='baiviet',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
    ]
